In [1]:
%pip install pandas
import pandas as pd

def clean_data(df):
    # Drop columns: 'Unnamed: 0', 'Unnamed: 15' and 5 other columns
    df = df.drop(columns=['Unnamed: 0', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20'])
    # Drop columns: 'Unnamed: 13', 'Unnamed: 14'
    df = df.drop(columns=['Unnamed: 13', 'Unnamed: 14'])
    # Fix unmatched parenthesis error
    df.at[3, 'Unnamed: 1'] = "Date "
    # Drop rows with missing data across all columns
    df = df.dropna()
    # Split text using string ' ' in columns: 'Unnamed: 2', 'Unnamed: 3' and 9 other columns
    loc_0 = df.columns.get_loc('Unnamed: 2')
    df_split = df['Unnamed: 2'].str.split(expand=True, n=1).add_prefix('Unnamed: 2_')
    df = pd.concat([df.iloc[:, :loc_0], df_split, df.iloc[:, loc_0:]], axis=1)
    loc_1 = df.columns.get_loc('Unnamed: 3')
    df_split = df['Unnamed: 3'].str.split(expand=True, n=1).add_prefix('Unnamed: 3_')
    df = pd.concat([df.iloc[:, :loc_1], df_split, df.iloc[:, loc_1:]], axis=1)
    loc_2 = df.columns.get_loc('Unnamed: 4')
    df_split = df['Unnamed: 4'].str.split(expand=True, n=1).add_prefix('Unnamed: 4_')
    df = pd.concat([df.iloc[:, :loc_2], df_split, df.iloc[:, loc_2:]], axis=1)
    loc_3 = df.columns.get_loc('Unnamed: 5')
    df_split = df['Unnamed: 5'].str.split(expand=True, n=1).add_prefix('Unnamed: 5_')
    df = pd.concat([df.iloc[:, :loc_3], df_split, df.iloc[:, loc_3:]], axis=1)
    loc_4 = df.columns.get_loc('Unnamed: 6')
    df_split = df['Unnamed: 6'].str.split(expand=True, n=1).add_prefix('Unnamed: 6_')
    df = pd.concat([df.iloc[:, :loc_4], df_split, df.iloc[:, loc_4:]], axis=1)
    loc_5 = df.columns.get_loc('Unnamed: 7')
    df_split = df['Unnamed: 7'].str.split(expand=True, n=1).add_prefix('Unnamed: 7_')
    df = pd.concat([df.iloc[:, :loc_5], df_split, df.iloc[:, loc_5:]], axis=1)
    loc_6 = df.columns.get_loc('Unnamed: 8')
    df_split = df['Unnamed: 8'].str.split(expand=True, n=1).add_prefix('Unnamed: 8_')
    df = pd.concat([df.iloc[:, :loc_6], df_split, df.iloc[:, loc_6:]], axis=1)
    loc_7 = df.columns.get_loc('Unnamed: 9')
    df_split = df['Unnamed: 9'].str.split(expand=True, n=1).add_prefix('Unnamed: 9_')
    df = pd.concat([df.iloc[:, :loc_7], df_split, df.iloc[:, loc_7:]], axis=1)
    loc_8 = df.columns.get_loc('Unnamed: 10')
    df_split = df['Unnamed: 10'].str.split(expand=True, n=1).add_prefix('Unnamed: 10_')
    df = pd.concat([df.iloc[:, :loc_8], df_split, df.iloc[:, loc_8:]], axis=1)
    loc_9 = df.columns.get_loc('Unnamed: 11')
    df_split = df['Unnamed: 11'].str.split(expand=True, n=1).add_prefix('Unnamed: 11_')
    df = pd.concat([df.iloc[:, :loc_9], df_split, df.iloc[:, loc_9:]], axis=1)
    loc_10 = df.columns.get_loc('Unnamed: 12')
    df_split = df['Unnamed: 12'].str.split(expand=True, n=1).add_prefix('Unnamed: 12_')
    df = pd.concat([df.iloc[:, :loc_10], df_split, df.iloc[:, loc_10:]], axis=1)
    df = df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12'])
    # Drop columns: 'Unnamed: 2_1', 'Unnamed: 3_1', 'Unnamed: 11_1'
    df = df.drop(columns=['Unnamed: 2_1', 'Unnamed: 3_1', 'Unnamed: 11_1'])
    # Remove leading and trailing whitespace in columns: 'Unnamed: 1', 'Unnamed: 2_0' and 10 other columns
    df['Unnamed: 1'] = df['Unnamed: 1'].str.strip()
    df['Unnamed: 2_0'] = df['Unnamed: 2_0'].str.strip()
    df['Unnamed: 3_0'] = df['Unnamed: 3_0'].str.strip()
    df['Unnamed: 4_0'] = df['Unnamed: 4_0'].str.strip()
    df['Unnamed: 5_0'] = df['Unnamed: 5_0'].str.strip()
    df['Unnamed: 6_0'] = df['Unnamed: 6_0'].str.strip()
    df['Unnamed: 7_0'] = df['Unnamed: 7_0'].str.strip()
    df['Unnamed: 8_0'] = df['Unnamed: 8_0'].str.strip()
    df['Unnamed: 9_0'] = df['Unnamed: 9_0'].str.strip()
    df['Unnamed: 10_0'] = df['Unnamed: 10_0'].str.strip()
    df['Unnamed: 11_0'] = df['Unnamed: 11_0'].str.strip()
    df['Unnamed: 12_0'] = df['Unnamed: 12_0'].str.strip()
    # First row is now column names
    df.columns = df.iloc[0]
    df = df[1:].reset_index(drop=True)
    # Replace all instances of "," with "" in columns: '2023/24', '2024/25' and 9 other columns
    df['2023/24'] = df['2023/24'].str.replace(",", "", case=False, regex=False)
    df['2024/25'] = df['2024/25'].str.replace(",", "", case=False, regex=False)
    df['2014/15'] = df['2014/15'].str.replace(",", "", case=False, regex=False)
    df['2015/16'] = df['2015/16'].str.replace(",", "", case=False, regex=False)
    df['2016/17'] = df['2016/17'].str.replace(",", "", case=False, regex=False)
    df['2017/18'] = df['2017/18'].str.replace(",", "", case=False, regex=False)
    df['2018/19'] = df['2018/19'].str.replace(",", "", case=False, regex=False)
    df['2019/20'] = df['2019/20'].str.replace(",", "", case=False, regex=False)
    df['2020/21'] = df['2020/21'].str.replace(",", "", case=False, regex=False)
    df['2021/22'] = df['2021/22'].str.replace(",", "", case=False, regex=False)
    df['2022/23'] = df['2022/23'].str.replace(",", "", case=False, regex=False)
    # Change column type to float64 for columns: '2023/24', '2024/25' and 9 other columns
    df = df.astype({'2023/24': 'float64', '2024/25': 'float64', '2014/15': 'float64', '2015/16': 'float64', '2016/17': 'float64', '2017/18': 'float64', '2018/19': 'float64', '2019/20': 'float64', '2020/21': 'float64', '2021/22': 'float64', '2022/23': 'float64'})
    # Set 'Date' column as index
    df.set_index('Date', inplace=True)
    # Transpose the DataFrame
    df = df.transpose()
    # Sort by column: index (ascending)
    df = df.sort_index()
    # Rename index column to 'Year'
    df.index.name = 'Year'
    # Save DataFrame to CSV file
    df.to_csv(r'c:\Users\abdel\OneDrive\Dokumente\GitHub\eg-mof-fisc\Data\clean_data.csv', index=True)
    return df

# Loaded variable 'df' from URI: c:\Users\abdel\OneDrive\Dokumente\GitHub\eg-mof-fisc\Data\Unclean.csv
df = pd.read_csv(r'c:\Users\abdel\OneDrive\Dokumente\GitHub\eg-mof-fisc\Data\Unclean.csv')

df_clean = clean_data(df.copy())
df_clean.head()

Requirement already satisfied: pandas in c:\users\abdel\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abdel\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abdel\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abdel\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abdel\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\abdel\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Date,Total Revenues,Tax Revenues,Income Tax,Property Taxes,Value Added Taxes,Taxes on International Trade,Other Taxes,Non-Tax Revenue,Grants,From Foreign Governments,...,"Subsidies, Grants and Social benefits",Other Expenditures,Purchases of Non-Financial assets,Total Cash Balance 4/,Net Acquisition of Financial assets,Overall Fiscal Balance,Overall Balance GDP (%) 5/,Primary Balance / GDP (%) 5/,Revenues/ GDP (%) 5/,Expenditure/ GDP (%) 5/
Year,,,,,,,,,,,,,,,,,,,,,
2014/15,465241.0,305957.0,129818.0,21107.0,122930.0,21867.0,10235.0,159284.0,25437.0,24942.0,...,198569.0,50279.0,61750.0,-268109.0,11321.0,-279430.0,-11.4,-3.5,19.0,30.0
2015/16,491488.0,352315.0,144743.0,27990.0,140525.0,28091.0,10966.0,139173.0,3543.0,3236.0,...,201024.0,54551.0,69250.0,-326356.0,13139.0,-339495.0,-12.5,-3.5,18.1,30.2
2016/17,659184.0,462007.0,166897.0,36539.0,208624.0,34255.0,15691.0,197177.0,17683.0,17040.0,...,276719.0,61517.0,109141.0,-372757.0,6833.0,-379590.0,-10.2,-1.7,19.0,29.7
2017/18,821134.0,629302.0,207230.0,51410.0,294257.0,37908.0,38497.0,191833.0,3194.0,1006.0,...,329379.0,74758.0,109680.0,-423274.0,9306.0,-432580.0,-9.1,0.1,17.2,26.1
2018/19,941910.0,736121.0,250080.0,58907.0,350576.0,42020.0,34538.0,205790.0,2609.0,1100.0,...,287461.0,77565.0,143342.0,-427960.0,1991.0,-429951.0,-7.5,1.8,16.5,23.9